CMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blogs/', include('blog.urls')),
    path('accounts/', include('account.urls')),
    path('tinymce/', include('tinymce.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path, re_path
# from blog.views import index
from blog.views import indexPage,PostListView,PostFormView,search_code,view_by_cat_button,BtnBlogDetails, contact, post_edit_form_view,post_details_view,like_post,PostFormUpdateView,PostFormDeleteView


urlpatterns = [
    # path("index", indexPage),
    path("", PostListView.as_view(template_name="blog/index.html"), name="index"),
    # path("postComment", postComment, name='postComment'),
    path("posts", PostFormView.as_view(template_name="blog/post.html"), name="post"),
    # path("posts", post_form_view),
    path("search/", search_code, name="search"),
    path("contact/", contact, name="contact"),
    path("filter/<int:id>", view_by_cat_button),
    path("filter/<slug:slug>", BtnBlogDetails.as_view()),
    path("<int:sno>", post_details_view, name="post-detail"),
    path("posts/<slug:slug>", PostFormUpdateView.as_view(), name="update-blog"),
    path("delete/<slug:slug>", PostFormDeleteView.as_view(),name="delete-blog"),
    path("like/<int:sno>", like_post, name="like_post")
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from account.models import Profile
from django.urls import reverse
from django.utils.text import slugify
from tinymce import models as tinymce_models
from django.utils.timezone import now

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()

    def __str__(self):
        return self.name


class Post(models.Model):
    statuses = [
        ("D", "Draft"),
        ("P", "Published"),
    ]
    sno = models.AutoField(primary_key=True)
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True,blank=True)
    content = tinymce_models.HTMLField()
    status = models.CharField(max_length=1, choices=statuses)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    image = models.ImageField(upload_to="blog/post", blank=True)
    likes = models.ManyToManyField(User, related_name='likes', blank=True)

    def __str__(self):
        return self.title

    def total_likes(self):
        return self.likes.count

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'sno': self.sno})

    def update_reverse_path(self):
        return reverse('update-blog', kwargs={'slug': self.slug})

    def delete_reverse_path(self):
        return reverse('delete-blog', kwargs={'slug': self.slug})


# class BlogComment(models.Model):
#     sno = models.AutoField(primary_key=True)
#     comment = models.TextField()
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     post = models.ForeignKey(Post, on_delete=models.CASCADE)
#     parent = models.ForeignKey('self', on_delete=models.CASCADE,null=True)
#     timestamp = models.DateTimeField(default=now)

#     def __str__(self):
#         return self.comment[0:20]+"..."+"by "+self.user.username


class ContactUs(models.Model):
    sno = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, blank=False)
    email = models.EmailField()
    phone = models.CharField(max_length=11, blank=False)
    message = models.TextField()

    def __str__(self):
        return self.name

account/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from account.models import Profile
from django.forms.widgets import PasswordInput, TextInput


class SignUpForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'email', 'first_name', 'last_name')


class ProfileUpdateForm(forms.ModelForm):
    bio = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Profile
        fields = ['display_name', 'image', 'bio']

blog/forms.py
from django import forms
from django.forms import ModelForm
import re
from blog.models import Post
from account.models import User
from tinymce.widgets import TinyMCE


class PostForm(ModelForm):
    content = forms.CharField(widget=TinyMCE(attrs={'cols': 50, 'rows': 25}))

    class Meta:
        model = Post
        fields = ['title', 'content', 'status', 'category',  'author', 'image']


class ContactForm(forms.Form):
    countries = [("IND", "INDIA"), ("CHN", "China")]
    name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={"class": "input-field", "placeholder": "Name"}))
    # password = forms.CharField(max_length=16, widget=forms.PasswordInput)
    email = forms.EmailField(required=False,widget=forms.TextInput(attrs={"placeholder": "Your Email"}))
    phone = forms.RegexField(regex="^[6-9][0-9]{9}$", label="Phone", error_messages={"invalid": "Please provide valid indian phone number."}, required=False,widget=forms.TextInput(attrs={"placeholder": "Your Mobile No."}))
    message = forms.CharField(max_length=500, widget=forms.Textarea(attrs={"placeholder": "Your Message"}))
    country = forms.ChoiceField(choices=countries)


def clean(self):
    cleaned_data = super().clean()
    email = cleaned_data.get("email")
    phone = cleaned_data.get("phone_number")

    if email == "" and phone == "":
        raise forms.ValidationError("Atleast email or phone number should be provided", code="Invalid")


def clean_password(self):
    password = self.cleaned_data.get("password")
    m = re.search("[A-Z]", password)
    if not m:
        raise forms.ValidationError("Atleast one uppercase", code="upper")
    else:
        return password

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from blog.forms import ContactForm
from blog.forms import PostForm
from django.views import View
from blog.models import Post, Category, ContactUs
from account.models import User,Profile
from django.views.generic import ListView,CreateView, DetailView,FormView, UpdateView,DeleteView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy,reverse


def like_post(request,sno):
    likes = get_object_or_404(Post, sno=request.POST.get('post_sno'))
    p = Post.objects.get(sno=request.POST.get('post_sno'))
    # post = Post()
    print(p.title)
    p.likes.add(request.user)
    # return HttpResponse("ok",{"title":p.title})
    return HttpResponseRedirect(reverse('post-detail',args=[int(request.POST.get('post_sno'))]))

def indexPage(request,*args,**kwargs):
    posts = Post.objects.all()
    return render(request, "blog/index.html", context={"posts": posts})
    # posts = Post.objects.filter(status="D")
    # post_titles = [post.title for post in posts]
    # title_str = ("\n\n").join(post_titles)
    # return HttpResponse(title_str)


class PostListView(ListView):
    model = Post
    queryset = Post.objects.all()
    template_name = "blog/index.html"
    context_object_name = "posts"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        # context['author'] = Author.objects.all()
        return context


class PostFormView(LoginRequiredMixin,CreateView):
    login_url = 'login'
    # model = Post
    template_name = 'blog/post.html'
    form_class = PostForm

    # def get_form_kwargs(self):
    #     kwargs = super().get_form_kwargs()
    #     user = User.objects.get(username= self.request.user)
    #     kwargs.update({'initial':{'author': user}})
    #     return kwargs
    #
    # def form_valid(self, form):
    #     form.instance.author = self.request.user
    #     return super().form_valid(form)


def search_code(request):
    search_term = ""
    articles = []
    if 'search' in request.GET:
        search_term = request.GET.get('search')
        posts = Post.objects.all()
        for post in posts:
            if search_term.lower() in post.title.lower() or search_term in post.title.lower():
                print(search_term)
                print(post.title)
                articles.append(post)
        # articles = Post.objects.filter(title=search_term)
        # print(articles)
        # print(search_term)
        return render(request, "blog/search.html", context={'articles': articles})
    else:
        return render(request, "blog/search.html")


def view_by_cat_button(request, id,*args,**kwargs):
    category = Category.objects.all()
    posts = Post.objects.filter(category__id=id)
    # print(posts)
    context = {
        'category': category,
        'posts': posts
        }
    return render(request, 'blog/cat_views.html', context)


class BtnBlogDetails(LoginRequiredMixin, DetailView):
    login_url = 'login'
    model = Post
    template_name = "blog/btn-details.html"


def post_details_view(request, sno):
    post = Post.objects.filter(sno=sno).first()
    # comments = BlogComment.objects.filter(post=post, parent=None)
    # replies = BlogComment.objects.filter(post=post).exclude(parent=None)
    # replyDict = {}
    # for reply in replies:
    #     if reply.parent.sno not in replyDict.keys():
    #         replyDict[reply.parent.sno] = [reply]
    #     else:
    #         replyDict[reply.parent.sno].append(reply)
    context = {'post': post, 'user': request.user}
    return render(request, 'blog/details.html', context)


# def like_post(request):
#     post = get_object_or_404(Post, request.POST.get('post_id'))
#     post.likes.add(request.user)
#     return HttpResponseRedirect(post.get_absolute_url())


# def postComment(request):
#     if request.method == 'POST':
#         comment = request.POST.get("comment")
#         user = request.user
#         postSno = request.POST.get("postSno")
#         parentSno = request.POST.get("parentSno")
#         post = Post.objects.get(sno=postSno)
#         if parentSno == "":
#             comment = BlogComment(comment=comment, user=user, post=post)
#             comment.save()
#         else:
#             parent = BlogComment.objects.get(sno=parentSno)
#             comment = BlogComment(comment=comment, user=user, post=post, parent=parent)
#             comment.save()
#         # messages.success(request, "your message has been post successfully!.")
#         return redirect(f"/blogs/{post.slug}")


class PostFormUpdateView(UpdateView):
    model = Post
    form_class = PostForm
    # success_url = "contact"
    template_name = "blog/post.html"

    # def get_form_kwargs(self):
    #     kwargs = super().get_form_kwargs()
    #     user = Profile.objects.get(username=self.request.user)
    #     kwargs.update({'initial': {'author': user}})
    #     return kwargs
    #
    # def form_valid(self, form):
    #     form.instance.author = self.request.user
    #     return super().form_valid(form)


class PostFormDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy('profile')
    template_name = "blog/confirm-delete.html"


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            print(form)
            instance = form.save(commit=False)
            instance.save()
            return HttpResponseRedirect('contact/')
        return render(request, 'blog/contact.html', context={"form": form})
    return render(request, 'blog/contact.html', context={"form": ContactForm})


    # def form_valid(self, form):
    #     return super().form_valid(form)


def Trending_Posts(request,*args,**kwargs):
    trending_posts = Trending_Posts.objects.all()
    print(trending_posts)
    return render(request, "blog/index.html", context={"trending_posts": trending_posts})


def post_edit_form_view(request,id,*args,**kwargs):
    try:
        post = Post.objects.get(id=id)
    except:
        return HttpResponse("Invalid Post ID")

    if request.method == "GET":
        form = PostForm(instance=post)
        return render(request, "blog/post.html", context={"form": form})
    else:
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return HttpResponse("welcome")

        return render(request, "blog/post.html", context={"form": form})
    return render(request, "blog/post.html", context={"form": form})


# def post_details(request,id,*args,**kwargs):
#     try:
#         post = Post.objects.get(id=id)
#         post_str = "{} \n\n {}".format(post.title,post.content)
#         return HttpResponse(post_str)
#     except:
#         return HttpResponse("Invalid Id")


# def contact_view(request,*args,**kwargs):
#     # print(request.method)
#     if request.method == "GET":
#         form = ContactForm()
#         return render(request, "blog/contact.html", context={"form": form})
#     else:
#         form = ContactForm(request.POST)
#         if form.is_valid():
#             print(form.cleaned_data)
#             return HttpResponse("thank you")
#         else:
#             return render(request, "blog/contact.html", context={"form": form})
#
#     form = ContactForm()
#     return render(request, "blog/contact.html", context={"form": form})

blog/templates/blog/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://fonts.googleapis.com/css?family=Poppins:500,600&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/35c398e458.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static  'blog/css/base.css' %}"> {% block extra_head %} {% endblock %}
</head>

<body style="min-height:100%;">

    <header id="myTopnav" class="topnav">
        <a href="{% url 'index' %}">
            <div class="Logo__Logo__2isxd Logo__Light__2EwPM">EDYODA</div>
            <div id="Logo__Stories__1BXR2">Stories</div>
        </a>
        <div class="search-box">
            <form method="get" action="{% url 'search' %}">
                <input id="search-input" type="text" name="search" placeholder="Type here">
                <button id="search-btn" type="submit">Search</button>
            </form>
        </div>
        <div id="username">
            {% if user.is_authenticated %}

            <a href="{% url 'profile'  %}"><b>Welcome &nbsp;&nbsp;{{ user.get_username }}&nbsp;|</b></a>&nbsp;&nbsp;&nbsp;&nbsp;
            <a class="Log" href="{% url 'logout' %}">&nbsp;Logout&nbsp;|</a> {% else %}
            <a href="{% url 'login' %}">&nbsp;Login |</a>&nbsp;&nbsp;
            <a href="{% url 'signup' %}">Signup&nbsp;|&nbsp;</a> {% endif %}
            <a href="{% url 'contact' %}">&nbsp;ContactUs&nbsp;|</a>&nbsp;
            <a href="{% url 'post' %}">&nbsp;Add Blog</a>
        </div>



    </header>
    <hr> {% block content %} {% endblock %}


</body>

<style>
    header {
        text-align: center;
        background-color: white;
        padding: 10px;
        height: 60px;
    }
    
    .Logo__Logo__2isxd {
        float: left;
        margin-top: 5px;
        margin-bottom: -3px;
        margin-left: 40px;
        font-family: Raleway, sans-serif;
        font-size: 32px;
        font-weight: 900;
        font-style: normal;
        font-stretch: normal;
        line-height: 1.08;
        letter-spacing: -.9px;
        color: #0084ff;
    }
    
    #Logo__Stories__1BXR2 {
        float: left;
        margin-top: 30px;
        object-fit: contain;
        font-family: Raleway, sans-serif;
        font-size: 1.15em;
        font-weight: 500;
        font-style: italic;
        font-stretch: normal;
        letter-spacing: .9px;
        color: #000;
        margin-left: -140px
    }
    
    #username {
        margin-top: 40px;
        margin-bottom: 20px;
        margin-left: 800px;
    }
    
    a {
        color: #33334d;
        font-family: "Times New Roman", Times, serif;
    }
    
    .search-box {
        margin-top: 30px;
        margin-bottom: 20px;
        position: absolute;
        margin-left: 400px;
    }
    
    #search-input {
        height: 27px;
        width: 240px;
        border: 1px solid skyblue;
        border-radius: 4px;
    }
    
    #search-btn {
        margin-left: -7px;
        height: 31px;
        border: 1px solid black;
        color: black;
        background-color: white;
        cursor: pointer;
        border-color: #2196F3;
        color: dodgerblue;
        border-radius: 4px;
    }
    
    #search-btn:hover {
        background-color: #2196F3;
        color: white;
    }
    
    body {
        background-color: #f2f6ff;
        font-family: Raleway, sans-serif;
    }
    
    .h1heading {
        padding-top: 20px;
        width: 45%;
        margin: 0px auto;
        font-family: 'Raleway';
    }
    
    #btn1 {
        width: 80%;
        margin: 0px auto;
        display: block;
    }
    
    .filterbuttonrow {
        width: 70%;
        margin: 15px 212px
    }
    
    .filterbuttons {
        background-color: #f2f6ff;
        border: 1px solid rgb(3, 156, 245);
        ;
        padding: 5px 15px;
        border-radius: 15px;
        color: rgb(3, 156, 245);
        font-family: 'Raleway';
        margin: 4px;
        cursor: pointer;
    }
    
    .groupblog {
        width: 80%;
        margin: 0px auto;
    }
    
    #inner-div {
        float: left;
        height: 400px;
        margin: 10px;
        margin-bottom: 10px;
        display: grid;
        box-sizing: unset;
        background-color: #fff;
        box-shadow: 0 5px 10px 0 rgba(0, 0, 0, .1);
        border-radius: 5px;
        border: 1px solid rgba(0, 168, 255, .3);
        overflow: hidden;
        transition: transform .5s ease;
    }
    
    #inner-div:hover {
        transform: scale(1.09);
    }
    
    .blog {
        background-size: cover;
        height: 400px;
        display: inline-block;
        background-color: white;
        text-decoration: none;
        <!-- box-shadow: 5px rgb(3, 163, 255);
        -->border: 1px solid #3377ff;
        border-top-left-radius: 5px;
        border-top-right-radius: 5px;
    }
    
    .blog-img {
        background-size: cover;
        border-top-left-radius: 5px;
        border-top-right-radius: 5px;
        border-bottom-left-radius: 0px;
        border-bottom-right-radius: 0px;
    }
    
    figcaption {
        background-color: white;
        width: 280px;
        min-height: 200px;
        overflow: hidden;
        padding: 12px;
        margin-top: -3px;
    }
    
    .blog-heading {
        background-size: cover;
        font-family: 'Raleway';
        text-align: left;
        margin: -10px 0px 0px 0px;
        padding: 0 0px;
        color: black;
    }
    
    .blog-author {
        font-style: italic;
        padding-left: 20px;
        display: inline-block;
        color: rgb(3, 156, 245);
        margin: -18px 0px 5px 0px;
        font-family: 'Raleway';
        font-size: 20px;
        font-weight: 500
    }
    
    .blog-publish-date {
        display: inline-block;
        margin: -18px 0px 0px 0px;
        font-family: 'Raleway';
        font-size: 16px;
    }
    
    .blog-para {
        background-size: cover;
        padding: 7px 15px 7px 15px;
        margin: -15px 20px 10px 10px;
        margin-bottom: ;
        font-family: 'Raleway';
        color: black;
        letter-spacing: 0.35px;
        line-height: 1.7;
        font-size: 15px;
    }
    
    button {
        border: 1px solid #0084ff;
        border-radius: 15px;
        color: #0084ff;
        background-color: #f2f6ff;
        padding-left: 10px;
        padding-right: 10px;
        padding-top: 5px;
        padding-bottom: 5px;
        margin-right: 5px;
        margin-bottom: 10px
    }
    
    #btn {
        border: 2px solid black;
        color: black;
        background-color: white;
        cursor: pointer;
        border-color: #2196F3;
        color: dodgerblue;
    }
    
    #btn:hover {
        background-color: #2196F3;
        color: white;
    }
    
    #mainbody {
        margin: 0px auto;
        width: 100%;
        position: absolute;
        background-color: #DCE1E6;
    }
    
    #mainbody1 {
        margin-top: 30px;
        margin-left: 240px;
        width: 60%;
        height: 100%;
        border: 1px skyblue;
        background-color: white;
        border-radius: 9px;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    }
    
    .storyimg {
        width: 100%;
        height: 300px;
        border-top-left-radius: 7px;
        border-top-right-radius: 7px;
    }
    
    .storydescription {
        width: 100%;
        height: 400px;
    }
    
    form-surrounding {
        width: 200px;
    }
    
    #django-form {
        width: 100%;
        height: 100vh;
        background-color: #83B5F5;
        text-align: center;
    }
    
    #contact-form {
        width: 600px;
        height: 600px;
        background-color: white;
        margin: 0px auto;
        padding: 40px;
        border: 1px solid #F2F3F4;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        background-color: #33334d;
    }
    
    #contact-form label {
        display: none;
    }
    
    ul {
        list-style-type: none;
    }
    
    #contact-form input {
        width: 250px;
        height: 30px;
        border-radius: 5px;
        border: none;
        background-color: #E5E7E9;
    }
    
    #id_message {
        background-color: #E5E7E9;
    }
    
    #id_country {
        width: 250px;
        height: 30px;
        background-color: #E5E7E9;
        border-radius: 5px;
    }
    
    #contact-form input[type='submit']:hover {
        background-color: #2196F3;
        color: white;
    }
    
    #login-form {
        width: 700px;
        height: 600px;
        margin-left: 0px auto;
        display: inline-block;
        padding: 20px;
        border: 1px solid #F2F3F4;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        background-color: #33334d;
    }
    
    #signup-form-tag {
        color: black;
        font-weight: 900;
        font-size: large;
    }
    
    #login-form label {
        margin-left: -140px;
        color: white;
    }
    
    #login-form input {
        width: 220px;
        height: 30px;
        border-radius: 5px;
        border: none;
    }
    
    #login-btn {
        padding-left: 90px;
    }
    
    #login-form input[type='submit'] {
        width: 220px;
        border: 1px solid black;
        color: black;
        background-color: white;
        cursor: pointer;
        border-color: #2196F3;
        color: dodgerblue;
        margin-top: 10px;
    }
    
    #login-form input[type='submit']:hover {
        background-color: #2196F3;
        color: white;
    }
    
    #Add-new-post {
        margin-left: 250px;
        width: 100%;
        height: 600px;
        background-color: #33334d;
    }
    
    #new-post-form {
        margin: 30px 50px 30px 50px;
        height: 100%;
    }
    
    #new-post-form input[type=text] {
        width: 280px;
        height: 30px;
        border-radius: 5px;
        border: none;
        margin-top: 20px;
    }
    
    #new-post-form input[type=submit] {
        width: 150px;
        height: 30px;
        border-radius: 5px;
        border: none;
        margin-top: 30px;
        background-color: white;
        cursor: pointer;
        border-color: #2196F3;
        color: dodgerblue;
    }
    
    #new-post-form input[type='submit']:hover {
        background-color: #2196F3;
        color: white;
    }
    
    #id_status {
        width: 280px;
        height: 30px;
        border-radius: 5px;
        border: none;
        margin-top: 30px;
        margin: 30px 0px 0px 30px;
    }
    
    #id_category {
        width: 280px;
        height: 30px;
        border-radius: 5px;
        border: none;
        margin: 30px 0px 0px 14px;
    }
    
    #id_content {
        border-radius: 5px;
        border: none;
        margin: 30px 0px 0px 30px;
    }
    
    #id_image {
        margin: 30px 0px 0px 30px;
    }
    
    #id_author {
        width: 280px;
        height: 30px;
        border-radius: 5px;
        border: none;
        margin: 30px 0px 0px 30px;
    }
    
    #delete-form input[type='submit'] {
        color: black;
        background-color: white;
        cursor: pointer;
        border-color: #2196F3;
        color: dodgerblue;
    }
    
    #login-form input[type='submit']:hover {
        background-color: #ff3300;
        color: white;
    }
    
    #cancel-btn {
        color: black;
        background-color: white;
        cursor: pointer;
        border-color: #2196F3;
        color: dodgerblue;
    }
    
    #cancel-btn:hover {
        background-color: #2196F3;
        color: white;
    }
    
    #profile-update-form input[type='text'] {
        width: 280px;
        height: 30px;
        border-radius: 5px;
        border: none;
        margin-top: 20px;
    }
    
    #profile-update-form label input[type='textarea'] {
        margin-right: -250px;
    }
    
    #id_bio {
        width: 280px;
        height: 70px;
        border-radius: 5px;
        border: none;
        margin-top: 20px;
        margin-left: 70px;
    }
    
    #id_image {
        margin-top: 20px;
    }
    
    #image_clear_id {
        border: none;
        margin-top: 20px;
        margin-left: -20px;
    }
    
    #profile-update-div {
        width: 600px;
        height: 600px;
        margin-left: 200px;
        padding: 40px;
        border: 1px solid #F2F3F4;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        background-color: #33334d;
    }
    
    #profile-update-form input[type='submit'] {
        border: 2px solid white;
    }
    
    #profile-update-form input[type='submit']:hover {
        background-color: #2196F3;
        color: white;
    }
    
    #footer {
        background-color: blue;
        color: white;
        font-size: 14px;
        letter-spacing: 0.5px;
        text-align: center;
        padding: 30px 0px;
        display: block;
        left: 0;
        bottom: 0;
        width: 100%;
    }
    
    @media screen and (max-width: 700px) {
        header a:not(:first-child) {
            display: none;
        }
        .topnav a.icon {
            float: right;
            display: block;
        }
    }
    
    @media screen and (max-width: 700px) {
        header.responsive {
            position: relative;
        }
        header.responsive a.icon {
            position: absolute;
            right: 0;
            top: 0;
        }
        header.responsive a {
            float: none;
            display: block;
            text-align: left;
        }
    }
</style>

<script>
    function myFunction() {
        var x = document.getElementById("myTopnav");
        if (x.className === "topnav") {
            x.className += " responsive";
        } else {
            x.className = "topnav";
        }
    }
</script>

</html>

blog/templates/blog/btn-details.html
{% extends 'blog/base.html' %}
{% load static %}

    <link href="https://fonts.googleapis.com/css?family=Poppins:500,600&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/35c398e458.js" crossorigin="anonymous"></script>
<!--    <link rel="stylesheet"  href="{% static  'blog/css/base.css' %}">-->

{% block content %}
            <div id="mainbody1">
                <img class="storyimg" src="{{ post.image.url }}"/>
                    <div class="storydescription">
                        <h1 class="h1heading">{{ post.title }}</h1><br><br>
                        <a href=""><span class="blog-author" style="color:blue">{{ post.author }}</span> </a>| 23 Jul 2019<br>
                        <p class="blog-para">{{ post.content|truncatechars:700|safe  }}</p>
                    </div>
            </div>
{% endblock %}

blog/templates/blog/confirm-delete.html
{% extends 'blog/base.html' %}

{% block content %}

    <div style="margin:50px 70px 50px 230px;width:900px;height:400px;border:1px solid;background-color: #cccccc;">
        <div style="margin:0px 70px 0px 0px;border:1px solid;width:100%;height:100%;">
        <form id="delete-form" method="post" style="padding:100px;">{% csrf_token %}
            <p style="font-size:20px;margin-bottom:40px;color:red;">Are you sure you want to delete <b style="color:black;font-size:20px;">"{{ object }}"</b>?</p>
            <input type="submit" value="Confirm" style="width:100px;height:30px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <a id="cancel-btn" href="{% url 'profile' %}" style="padding:5px 18px 5px 18px;border:1px solid;">Cancel</a>
        </form>
            </div>
    </div>
{% endblock %}
<style>

</style>