blog/urls.py
from django.urls import path, re_path
# from blog.views import index
from blog.views import indexPage, PostListView, PostFormView, search_code, view_by_cat_button, BtnBlogDetails, contact, post_edit_form_view, post_details_view, like_post, PostFormUpdateView, postComment


urlpatterns = [
    # path("index", indexPage),
    path("", PostListView.as_view(template_name="blog/index.html"), name="index"),
    # path("postComment", postComment, name='postComment'),
    path("posts", PostFormView.as_view(template_name="blog/post.html"), name="post"),
    # path("posts", post_form_view),
    path("search/", search_code, name="search"),
    path("contact/", contact, name="contact"),
    path("like/<int:sno>", like_post, name="like_post"),
    path("<int:sno>", post_details_view, name="post-detail"),
    path("filter/<int:id>", view_by_cat_button),
    path("filter/<slug:slug>", BtnBlogDetails),
    path("posts/<slug:slug>", PostFormUpdateView.as_view(), name="update-blog"),
    # path("delete/<slug:slug>", PostFormDeleteView.as_view(),name="delete-blog"),
    path('comment', postComment, name="postComment")
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from account.models import Profile
from django.urls import reverse
from django.utils.text import slugify
from tinymce import models as tinymce_models
from django.utils.timezone import now

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()

    def __str__(self):
        return self.name


class Post(models.Model):
    statuses = [
        ("D", "Draft"),
        ("P", "Published"),
    ]
    sno = models.AutoField(primary_key=True)
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True,blank=True)
    content = tinymce_models.HTMLField()
    status = models.CharField(max_length=1, choices=statuses)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category')
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='author')
    date = models.DateField(auto_now_add=True)
    image = models.ImageField(upload_to="blog/post", blank=True)
    likes = models.ManyToManyField(User, related_name='likes', blank=True)

    def __str__(self):
        return self.title

    def total_likes(self):
        return self.likes.count()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'sno': self.sno})

    def update_reverse_path(self):
        return reverse('update-blog', kwargs={'slug': self.slug})

    def delete_reverse_path(self):
        return reverse('delete-blog', kwargs={'slug': self.slug})


class BlogComment(models.Model):
    sno = models.AutoField(primary_key=True)
    comment = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='commenter')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post')
    parent = models.ForeignKey('self', on_delete=models.CASCADE,null=True)
    timestamp = models.DateTimeField(default=now)

    def __str__(self):
        return self.comment[0:20]+"..."+"by "+self.user.username


class ContactUs(models.Model):
    sno = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, blank=False)
    email = models.EmailField()
    phone = models.CharField(max_length=11, blank=False)
    message = models.TextField()

    def __str__(self):
        return self.name

blog/templates/blog/base.html
{% load static %}
{% csrf_token %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <title>Title</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" />
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>
  <link href="https://fonts.googleapis.com/css?family=Poppins:500,600&display=swap" rel="stylesheet" />
  <script src="https://kit.fontawesome.com/35c398e458.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{% static  'blog/css/base.css' %}" />
  {% block extra_head %} {% endblock %}
</head>

<body>
  <div>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'index' %}">Tech Stories</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'contact' %}">ContactUs</a>
          </li>

          {% if user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="{% url 'profile'  %}" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="true">{{ user.get_username }}</a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li>
                  <a class="dropdown-item" href="{% url 'profile' %}">profile</a>
                </li>
                <li>
                  <a class="dropdown-item" href="{% url 'logout' %}">logout</a>
                </li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'post' %}">Add Blog</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'signup' %}">Signup</a>
            </li>
          {% endif %}
        </ul>
        <form class="d-flex" method="get" action="{% url 'search' %}">
          <input class="form-control me-1" name="search" type="search" placeholder="Search" aria-label="Search" />
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

  <hr />
 
    {% block content %}
    {% endblock %}

  </div>
</body>

  
    
  <style>
    body {
      background-color: #f2f6ff;
      font-family: Raleway, sans-serif;
    }
  
    p {
      font-size: 13px;
    }
  
    .form-control {
      height: 47px;
    }
  
    .h1heading {
      padding-top: 20px;
      width: 45%;
      margin: 0px auto;
      font-family: "Raleway";
    }
  
    #btn1 {
      width: 80%;
      margin: 0px auto;
      display: block;
    }
  
    .filterbuttonrow {
      width: 70%;
      margin: 15px 212px;
    }
  
    .filterbuttons {
      background-color: #f2f6ff;
      border: 1px solid rgb(3, 156, 245);
      padding: 5px 15px;
      border-radius: 15px;
      color: rgb(3, 156, 245);
      font-family: "Raleway";
      margin: 4px;
      cursor: pointer;
    }
  
    .groupblog {
      width: 80%;
      margin: 0px auto;
    }
  
    #inner-div {
      float: left;
      height: 400px;
      margin: 10px;
      margin-bottom: 10px;
      display: grid;
      box-sizing: unset;
      background-color: #fff;
      box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.1);
      border-radius: 5px;
      border: 1px solid rgba(0, 168, 255, 0.3);
      overflow: hidden;
      transition: transform 0.5s ease;
    }
  
    #inner-div:hover {
      transform: scale(1.09);
    }
  
    .blog {
      background-size: cover;
      height: 400px;
      display: inline-block;
      background-color: white;
      text-decoration: none;
      border: 1px solid #3377ff;
      border-top-left-radius: 5px;
      border-top-right-radius: 5px;
    }
  
    .blog-img {
      background-size: cover;
      border-top-left-radius: 5px;
      border-top-right-radius: 5px;
      border-bottom-left-radius: 0px;
      border-bottom-right-radius: 0px;
    }
  
    figcaption {
      background-color: white;
      width: 280px;
      min-height: 200px;
      overflow: hidden;
      padding: 12px;
      margin-top: -3px;
    }
  
    .blog-heading {
      background-size: cover;
      font-family: "Raleway";
      text-align: left;
      margin: -10px 0px 0px 0px;
      padding: 0 0px;
      color: black;
    }
  
    .blog-author {
      font-style: italic;
      padding-left: 20px;
      display: inline-block;
      color: rgb(3, 156, 245);
      margin: -18px 0px 5px 0px;
      font-family: "Raleway";
      font-size: 20px;
      font-weight: 500;
    }
  
    .blog-publish-date {
      display: inline-block;
      margin: -18px 0px 0px 0px;
      font-family: "Raleway";
      font-size: 16px;
    }
  
    .blog-para {
      background-size: cover;
      padding: 7px 15px 7px 15px;
      margin: -15px 20px 10px 10px;
      /* margin-bottom: ; */
      font-family: "Raleway";
      color: black;
      letter-spacing: 0.35px;
      line-height: 1.7;
      font-size: 15px;
    }
  
    button {
      border: 1px solid #0084ff;
      border-radius: 15px;
      color: #0084ff;
      background-color: #f2f6ff;
      padding-left: 10px;
      padding-right: 10px;
      padding-top: 5px;
      padding-bottom: 5px;
      margin-right: 5px;
      margin-bottom: 10px;
    }
  
    #btn {
      border: 2px solid black;
      color: black;
      background-color: white;
      cursor: pointer;
      border-color: #2196f3;
      color: dodgerblue;
    }
  
    #btn:hover {
      background-color: #2196f3;
      color: white;
    }
  
    #mainbody {
      margin: 0px auto;
      width: 100%;
      position: absolute;
      background-color: #dce1e6;
    }
  
    #mainbody1 {
      margin-top: 30px;
      margin-left: 240px;
      width: 60%;
      height: 100%;
      border: 1px skyblue;
      background-color: white;
      border-radius: 9px;
      box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2),
        0 6px 20px 0 rgba(0, 0, 0, 0.19);
    }
  
    .storyimg {
      width: 100%;
      height: 300px;
      border-top-left-radius: 7px;
      border-top-right-radius: 7px;
    }
  
    .storydescription {
      width: 100%;
      height: 400px;
    }
  
    form-surrounding {
      width: 200px;
    }
  
    #django-form {
      width: 100%;
      height: 100vh;
      background-color: #83b5f5;
      text-align: center;
    }
  
    #contact-form {
      width: 600px;
      height: 600px;
      background-color: white;
      margin: 0px auto;
      padding: 40px;
      border: 1px solid #f2f3f4;
      box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2),
        0 6px 20px 0 rgba(0, 0, 0, 0.19);
      background-color: #33334d;
    }
  
    #contact-form label {
      display: none;
    }
  
    ul {
      list-style-type: none;
    }
  
    #contact-form input {
      width: 250px;
      height: 30px;
      border-radius: 5px;
      border: none;
      background-color: #e5e7e9;
    }
  
    #id_message {
      background-color: #e5e7e9;
    }
  
    #id_country {
      width: 250px;
      height: 30px;
      background-color: #e5e7e9;
      border-radius: 5px;
    }
  
    #contact-form input[type="submit"]:hover {
      background-color: #2196f3;
      color: white;
    }
  
    #login-form {
      width: 700px;
      height: 600px;
      margin-left: 0px auto;
      display: inline-block;
      padding: 20px;
      border: 1px solid #f2f3f4;
      box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2),
        0 6px 20px 0 rgba(0, 0, 0, 0.19);
      background-color: #33334d;
    }
  
    #signup-form-tag {
      color: black;
      font-weight: 900;
      font-size: large;
    }
  
    #login-form label {
      margin-left: -140px;
      color: white;
    }
  
    #login-form input {
      width: 220px;
      height: 30px;
      border-radius: 5px;
      border: none;
    }
  
    #login-btn {
      padding-left: 90px;
    }
  
    #login-form input[type="submit"] {
      width: 220px;
      border: 1px solid black;
      color: black;
      background-color: white;
      cursor: pointer;
      border-color: #2196f3;
      color: dodgerblue;
      margin-top: 10px;
    }
  
    #login-form input[type="submit"]:hover {
      background-color: #2196f3;
      color: white;
    }
  
    #Add-new-post {
      margin-left: 250px;
      width: 100%;
      height: 600px;
      background-color: #33334d;
    }
  
    #new-post-form {
      margin: 30px 50px 30px 50px;
      height: 100%;
    }
  
    #new-post-form input[type="text"] {
      width: 280px;
      height: 30px;
      border-radius: 5px;
      border: none;
      margin-top: 20px;
    }
  
    #new-post-form input[type="submit"] {
      width: 150px;
      height: 30px;
      border-radius: 5px;
      border: none;
      margin-top: 30px;
      background-color: white;
      cursor: pointer;
      border-color: #2196f3;
      color: dodgerblue;
    }
  
    #new-post-form input[type="submit"]:hover {
      background-color: #2196f3;
      color: white;
    }
  
    #id_status {
      width: 280px;
      height: 30px;
      border-radius: 5px;
      border: none;
      margin-top: 30px;
      margin: 30px 0px 0px 30px;
    }
  
    #id_category {
      width: 280px;
      height: 30px;
      border-radius: 5px;
      border: none;
      margin: 30px 0px 0px 14px;
    }
  
    #id_content {
      border-radius: 5px;
      border: none;
      margin: 30px 0px 0px 30px;
    }
  
    #id_image {
      margin: 30px 0px 0px 30px;
    }
  
    #id_author {
      width: 280px;
      height: 30px;
      border-radius: 5px;
      border: none;
      margin: 30px 0px 0px 30px;
    }
  
    #delete-form input[type="submit"] {
      color: black;
      background-color: white;
      cursor: pointer;
      border-color: #2196f3;
      color: dodgerblue;
    }
  
    #login-form input[type="submit"]:hover {
      background-color: #ff3300;
      color: white;
    }
  
    #cancel-btn {
      color: black;
      background-color: white;
      cursor: pointer;
      border-color: #2196f3;
      color: dodgerblue;
    }
  
    #cancel-btn:hover {
      background-color: #2196f3;
      color: white;
    }
  
    #profile-update-form input[type="text"] {
      width: 280px;
      height: 30px;
      border-radius: 5px;
      border: none;
      margin-top: 20px;
    }
  
    #profile-update-form label input[type="textarea"] {
      margin-right: -250px;
    }
  
    #id_bio {
      width: 280px;
      height: 70px;
      border-radius: 5px;
      border: none;
      margin-top: 20px;
      margin-left: 70px;
    }
  
    #id_image {
      margin-top: 20px;
    }
  
    #image_clear_id {
      border: none;
      margin-top: 20px;
      margin-left: -20px;
    }
  
    #profile-update-div {
      width: 600px;
      height: 600px;
      margin-left: 200px;
      padding: 40px;
      border: 1px solid #f2f3f4;
      box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2),
        0 6px 20px 0 rgba(0, 0, 0, 0.19);
      background-color: #33334d;
    }
  
    #profile-update-form input[type="submit"] {
      border: 2px solid white;
    }
  
    #profile-update-form input[type="submit"]:hover {
      background-color: #2196f3;
      color: white;
    }
  
    #footer {
      background-color: blue;
      color: white;
      font-size: 14px;
      letter-spacing: 0.5px;
      text-align: center;
      padding: 30px 0px;
      display: block;
      left: 0;
      bottom: 0;
      width: 100%;
    }
  
    @media screen and (max-width: 700px) {
      header a:not(:first-child) {
        display: none;
      }
  
      .topnav a.icon {
        float: right;
        display: block;
      }
    }
{% comment %}   
    @media screen and (max-width: 700px) {
      header.responsive {
        position: relative;
      }
  
      header.responsive a.icon {
        position: absolute;
        right: 0;
        top: 0;
      }
  
      header.responsive a {
        float: none;
        display: block;
        text-align: left;
      }
    } {% endcomment %}
  </style>
</html>

blog/templates/blog/cat_views.html
{% extends 'blog/base.html' %}
{% load static %}

<link href="https://fonts.googleapis.com/css?family=Poppins:500,600&display=swap" rel="stylesheet">
<script src="https://kit.fontawesome.com/35c398e458.js" crossorigin="anonymous"></script>
   <link rel="stylesheet"  href="{% static  'blog/css/base.css' %}">

{% block content %}


<div class="container">
    <div id="">
        <div id="trending-posts">
            <h5>Trending Posts</h5>
        </div>
        <div id="trending-posts">
            {% for cat in category %}
                <a href="{{ cat.id }}" id="cat-button"><button id="btn">{{ cat.name }}</button></a>
            {% endfor %}
        </div>
    </div>


    <div class="row  row-cols-md-3 g-4">
        {% for post in posts %}
            <div class="col">
                <a href="{{ post.slug }}">
                    <div class="card h-100">
                        {% if post.image %}
                            <img src="{{ post.image.url }}" class="card-img-top" alt="{{ post.title }}">
                        {% else %}
                            <div class="card-img-top" style="background-color: #f0f0f0; min-height: 200px; display: flex; align-items: center; justify-content: center;">
                                <span style="color: #999;">No Image</span>
                            </div>
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title"><strong>{{ post.title }}</strong></h5>
                            <h6 class="post-author text-info">{{post.author}}&nbsp;|&nbsp;</h6>
                            <p class="post-date text-dark" style="font-size: 12px;">{{ post.date }}</p>
                            <p class="card-text text-dark" >{{ post.content|truncatechars:150|safe }}</p>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>


<style>
    .container {
        margin: auto;
    }

    #trending-posts {
        margin: 0px auto;
        width: 80%;
    }

    #cat-button {
        font-size: 12px;
    }

    .row {
        margin: 0px auto;
        width: 80%;
    }

    .card-title {
        font-size: 19px;
    }

    h6 {
        margin-right: 50px;
    }

    #card-text {
        font-size: 15px;
    }

    .post-author {
        font-size: 15px;
    }

    .post-date {
        margin-top: -30px;
        margin-left: 80px;
    }
</style>

{% endblock %}

blog/templates/blog/details.html
{% extends 'blog/base.html' %}
{% load static %}
{% load humanize %}
{% load extras %}





{% block content %}



<div class="card mb-3">
    {% if post.image %}
        <img class="card-img-top" src="{{ post.image.url }}" alt="{{ post.title }}">
    {% endif %}
    <div class="card-body">
        <h5 class="card-title text-dark">{{ post.title }}</h5>
        <p class="card-text text-primary">{{ post.author }}&nbsp;|&nbsp;<span class=" post-date text-dark">{{ post.date }}</span></small></p>
        {% if user.is_authenticated %}
            <form method="post" action="{% url 'like_post' post.sno %}">
                {% csrf_token %}
                <button type="submit" name="post_sno" value="{{ post.sno }}" class="btn btn-primary btn-sm"
                    style="height: 40px;width: 60px;">like</button>-<small class="text-small text-primary">{{ total_likes }}
                    Likes</small>
            </form>
        {% else %}
            <form method="post" action="{% url 'like_post' post.sno %}">
                {% csrf_token %}
                <button type="submit" name="post_sno" value="{{ post.sno }}" class="btn btn-primary btn-sm"
                    style="height: 40px;width: 60px;" disabled>like</button>-<small class="text-small text-primary">{{ total_likes }}
                    Please login first.</small>
            </form>

        {% endif %}
        <p class="card-text text-dark">{{ post.content|safe }}</p>

    </div>
    <hr>
    <div class="container" style="width: 100%;">
        <div>
            <h5>Comments:({{ comments.count }})</h5>
            {% if user.is_authenticated %}
            <form method="post" action="{% url 'postComment' %}">
                <div class="mb-3">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" class="form-control" name="comment" placeholder="Entetr your comments" />
                    </div>
                    <input type="hidden" name="postSno" value="{{ post.sno }}" />
                    <input type="hidden" name="parentSno" value=""/>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
            {% else %}
            Please login to post a comment.
            {%endif%}
        </div>
        <hr>
        {% for comment in comments %}
            <div class="row my-3">
                <div class="user-image col-md-1">
                    <i class="fas fa-users my-3"></i>
                    <!-- <img class="user-image rounded mx-auto d-block" src="/media/profile/user.jpeg" alt="user" style="height:100%;width:100%;"/> -->
                </div>
                <div class="user-name col-md-11">
                    <b style="font-size: 13px;">{{ comment.user.username }}</b>&nbsp;<span class="bg-secondary rounded text-light" style="font-size: 11px;"><b>{{ comment.timestamp | naturaltime }}</b></span>
                    <div style="font-size: 13px;">{{ comment.comment }}</div>
                    <div class="reply mx-0">
                        {% if user.is_authenticated %}
                            <button class="btn btn-sm btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#replyBox{{comment.sno}}" aria-expanded="false" aria-controls="replyBox{{comment.sno}}">
                              Reply
                            </button>
                        
                          <div class="collapse" id="replyBox{{comment.sno}}">
                            <!-- <div class="card card-body my-2"> -->
                                <form method="post" action="{% url 'postComment' %}">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <!-- <label for="comment">Post a reply</label> -->
                                            <input type="text" class="form-control" name="comment" placeholder="Enter your reply" />
                                            <input type="hidden" name="parentSno" value="{{comment.sno}}"/>
                                        </div>
                                        <input type="hidden" name="postSno" value="{{ post.sno }}" />
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                </form>
                            <!-- </div> -->
                          </div>
                        {% else %}
                          <button class="btn btn-sm btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#replyBox{{comment.sno}}" aria-expanded="false" aria-controls="replyBox{{comment.sno}}" disabled>
                            Login for reply
                          </button>
                        {% endif %}
                        <div class="replies my-2">
                            {% for reply in replyDict|get_val:comment.sno %}
                                <div class="row my-2">
                                    <div class="user-image col-md-1">
                                        <i class="fas fa-users my-3"></i>
                                        <!-- <img class="user-image rounded mx-auto d-block" src="/media/profile/user.jpeg" alt="user"/> -->
                                    </div>
                                
                                    <div class="col-md-11 text-small">
                                        <b style="font-size: 13px;">{{ reply.user.username }}</b>&nbsp;<span class="bg-secondary rounded text-light" style="font-size: 11px;"><b>{{ reply.timestamp | naturaltime }}</b></span>
                                        <div style="font-size: 13px;">{{ reply.comment }}</div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

<style>
    .card {
        width: 54%;
        margin: 0px auto;
    }

    .card-img-top {
        height: 30%;
    }

    .post-date {
        font-size: 13px;
    }

    /* .user-image{
        height: 41 px;
        width: 53 px;
        border-radius: 8 px;
    } */
</style>



{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load static %}




{% block content %}


<div class="container">
    <div id="trending-posts-container">
        <div id="trending-posts">
            <h5>Trending Posts</h5>
        </div>
        <div id="trending-posts">
            {% for cat in categories %}
            <a href="filter/{{ cat.id }}" id="cat-button"><button id="btn">{{ cat.name }}</button></a>
            {% endfor %}
        </div>
    </div>


    {% comment %} <div class="row ">
        {% for post in posts %} {% endcomment %}
            {% comment %} <div class="col" style="display: inline-flex;">
                <a href="{{ post.get_absolute_url }}">
                    <div class="card h-100">
                        <img src="{{ post.image.url }}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title"><strong>{{ post.title }}</strong></h5>
                            <h6 class="post-author text-info">{{ post.author }}&nbsp;|&nbsp;</h6><p class="post-date" style="font-size: 15px;">{{ post.date }}</p>
                            <span class="card-text text-dark">{{ post.content|safe|truncatechars:350 }}</span>
                        </div>
                    </div>
                </a>
            </div> {% endcomment %}


            <div class="card-group">
                {% for post in posts %}
                    <div class="card col-md-4">
                        <a href="{{ post.get_absolute_url }}">
                        {% if post.image %}
                            <img src="{{post.image.url}}" class="card-img-top" alt="{{post.title}}">
                        {% else %}
                            <div class="card-img-top" style="background-color: #f0f0f0; min-height: 200px; display: flex; align-items: center; justify-content: center;">
                                <span style="color: #999;">No Image</span>
                            </div>
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{post.title}}</h5>
                            <div class="card-footer">
                                <small class="text-primary">{{post.author}}&nbsp;&nbsp;|&nbsp;&nbsp;{{post.date}}</small>
                            </div>
                            <p class="card-text">{{post.content|safe}}</p>
                        </div>
                        
                    </a>
                    </div>
                {% endfor %}
                
    {% comment %} </div> {% endcomment %}
</div>


<style>
    .container{
        width: 100%;
        left: 0;
        right: 0;
        margin: auto;
        overflow: hidden;
    }

    #trending-posts-container{
        margin: auto;
        width: 80%;
    }

    #trending-posts{
        overflow: hidden;
        width: 100%;
    }

    #cat-button{
        font-size: 12px;
    }

 
    
    

</style>

{% endblock %}

blog/templates/blog/search.html
{% extends 'blog/base.html' %}

{% block content %}

    <div class="groupblog">
                {% for article in articles %}
                <div id="inner-div">
                    <a class="blog" href="{% url 'post-detail' article.sno %}">
                        {% if article.image %}
                            <img class="blog-img" src="{{ article.image.url }}" alt="{{ article.title }}"/>
                        {% else %}
                            <div class="blog-img" style="background-color: #f0f0f0; min-height: 200px; display: flex; align-items: center; justify-content: center;">
                                <span style="color: #999;">No Image</span>
                            </div>
                        {% endif %}
                        <figcaption style="width:100%;height:100%;">
                            <b class="blog-heading">{{ article.title }}</b><br><br>
                            <span style="color:blue;padding:15px;">{{ article.author }}</span> | {{article.date}}<br>
                            <p class="blog-para">{{ article.content|safe|truncatechars:300  }}</p>
                        </figcaption>
                    </a>
                </div>
                {% endfor %}
            </div>
{% endblock %}